//! ART (Android Runtime) Hook 生成器
//!
//! Phase 4：实现 ART method hook 的代码生成与注入。
//!
//! 创新点（与 Magisk Zygisk / Xposed 完全不同）：
//! - 不修改 ART 内部数据结构（避免 ART 版本兼容问题）
//! - 通过生成 DEX 文件 + ClassLoader 注入实现方法替换
//! - 模块的 hook.toml 声明 → 自动生成 Java 代理类 → 注入到目标 app
//!
//! 工作流程：
//! 1. 解析 hook.toml 得到 HookEntry 列表
//! 2. 为每个 HookEntry 生成对应的 Java 代理方法（含 before/after/replace 逻辑）
//! 3. 把代理方法编译为 DEX 字节码
//! 4. 通过 ClassLoader 注入到目标 app
//! 5. ART 调用代理方法时，通过 IPC 转发给 companion 进程执行真实 handler
//!
//! 不抄 Magisk/Xposed 的部分：
//! - Xposed: 修改 ART Method 的 entry_point_，需要 ART 内部偏移
//! - Zygisk: LD_PRELOAD + Riru 风格 vtable hook
//! - NexusHook: DEX 注入 + ClassLoader 替换，纯 Java 层 hook

use crate::hook_table::{HookEntry, HookTable, HookType};
use std::collections::HashMap;

/// ART Hook 生成器
pub struct ArtHookGenerator {
    /// 已生成的代理类（class_name → Java 源码）
    pub generated_classes: HashMap<String, String>,
}

impl ArtHookGenerator {
    /// 创建新生成器
    pub fn new() -> Self {
        Self {
            generated_classes: HashMap::new(),
        }
    }

    /// 为 HookTable 生成所有代理类
    ///
    /// 返回 (类名, Java 源码) 列表，后续编译为 DEX
    pub fn generate(&mut self, table: &HookTable, module_id: &str) -> Vec<(String, String)> {
        let mut result = Vec::new();

        // 按 target_class 分组
        let mut by_class: HashMap<String, Vec<&HookEntry>> = HashMap::new();
        for entry in &table.entries {
            by_class
                .entry(entry.target_class.clone())
                .or_default()
                .push(entry);
        }

        // 为每个 target_class 生成一个代理类
        for (class_name, entries) in &by_class {
            let proxy_class_name = self.make_proxy_class_name(module_id, class_name);
            let java = self.generate_proxy_class(&proxy_class_name, class_name, entries, module_id);
            self.generated_classes
                .insert(proxy_class_name.clone(), java.clone());
            result.push((proxy_class_name, java));
        }

        result
    }

    /// 生成代理类名
    ///
    /// 规则：NexusHook_<module_id>_<class_name_hash>
    /// 例如：NexusHook_my_mod_a1b2c3d4
    fn make_proxy_class_name(&self, module_id: &str, target_class: &str) -> String {
        let hash = crate::util::hash_path(target_class);
        format!("NexusHook_{}_{}", module_id, &hash[..8])
    }

    /// 生成单个代理类的 Java 源码
    fn generate_proxy_class(
        &self,
        proxy_class_name: &str,
        target_class: &str,
        entries: &[&HookEntry],
        module_id: &str,
    ) -> String {
        let mut java = String::new();

        // 包声明
        java.push_str("package com.nexus.hook.generated;\n\n");

        // 导入
        java.push_str("import com.nexus.hook.runtime.HookBridge;\n");
        java.push_str("import java.lang.reflect.Method;\n\n");

        // 类声明
        java.push_str(&format!(
            "/**\n * Auto-generated by NexusHook ART Hook Generator\n * Module: {}\n * Target: {}\n */\n",
            module_id, target_class
        ));
        java.push_str(&format!("public class {} {{\n", proxy_class_name));
        java.push_str("    private static final String MODULE_ID = \"");
        java.push_str(module_id);
        java.push_str("\";\n\n");

        // 为每个 hook entry 生成代理方法
        for (i, entry) in entries.iter().enumerate() {
            let method_code = self.generate_proxy_method(entry, i, module_id);
            java.push_str(&method_code);
            java.push('\n');
        }

        // 静态初始化块：注册所有 hook
        java.push_str("    static {\n");
        java.push_str("        try {\n");
        for (i, entry) in entries.iter().enumerate() {
            java.push_str(&format!(
                "            registerHook_{}(\"{}\", \"{}\", \"{}\");\n",
                i, entry.target_class, entry.target_method, entry.signature
            ));
        }
        java.push_str("        } catch (Exception e) {\n");
        java.push_str(
            "            HookBridge.logError(\"Failed to register hooks: \" + e.getMessage());\n",
        );
        java.push_str("        }\n");
        java.push_str("    }\n\n");

        // 注册方法
        for (i, entry) in entries.iter().enumerate() {
            java.push_str(&format!(
                "    private static void registerHook_{}(String cls, String method, String sig) throws Exception {{\n",
                i
            ));
            java.push_str("        Class<?> targetClass = Class.forName(cls);\n");
            java.push_str("        // 通过 HookBridge 注册 ART method hook\n");
            java.push_str(&format!(
                "        HookBridge.registerHook(targetClass, method, sig, MODULE_ID, {}, \n",
                i
            ));
            java.push_str("            (hookId, args) -> {\n");
            java.push_str("                // 调用 companion 进程的 handler\n");
            java.push_str(&format!(
                "                return HookBridge.callHandler(MODULE_ID, {}, args);\n",
                i
            ));
            java.push_str("            });\n");
            java.push_str("    }\n\n");
        }

        java.push_str("}\n");
        java
    }

    /// 生成单个代理方法
    fn generate_proxy_method(&self, entry: &HookEntry, hook_id: usize, module_id: &str) -> String {
        let mut method = String::new();

        // 方法签名解析：从 JVM signature (Ljava/lang/String;)V 提取参数类型与返回类型
        let (param_types, return_type) = self.parse_signature(&entry.signature);

        // 生成代理方法
        method.push_str(&format!(
            "    // Hook #{}: {}.{} {}\n",
            hook_id, entry.target_class, entry.target_method, entry.signature
        ));
        method.push_str(&format!(
            "    // Type: {:?}, Handler: {}\n",
            entry.hook_type, entry.handler
        ));
        method.push_str(&format!(
            "    public static {} proxy_{}({}) {{\n",
            return_type,
            hook_id,
            self.format_params(&param_types)
        ));

        match entry.hook_type {
            HookType::Before => {
                // 在原方法前调用 handler
                method.push_str(&format!(
                    "        HookBridge.callHandler(MODULE_ID, {}, new Object[]{{ {} }});\n",
                    hook_id,
                    self.format_args(&param_types)
                ));
                method.push_str(&self.generate_original_call(
                    &entry.target_method,
                    &param_types,
                    &return_type,
                ));
            }
            HookType::After => {
                // 先调用原方法，再调用 handler
                method.push_str(&self.generate_original_callWithReturn(
                    &entry.target_method,
                    &param_types,
                    &return_type,
                    "result",
                ));
                method.push_str(&format!(
                    "        HookBridge.callHandler(MODULE_ID, {}, new Object[]{{ result }});\n",
                    hook_id
                ));
                method.push_str("        return result;\n");
            }
            HookType::Replace => {
                // 完全替换原方法
                method.push_str(&format!(
                    "        Object result = HookBridge.callHandler(MODULE_ID, {}, new Object[]{{ {} }});\n",
                    hook_id,
                    self.format_args(&param_types)
                ));
                method.push_str(&self.generate_return_from_object(&return_type, "result"));
            }
            HookType::Around => {
                // 前后都调用 handler
                method.push_str(&format!(
                    "        HookBridge.callHandler(MODULE_ID, {}, new Object[]{{ \"before\", {} }});\n",
                    hook_id,
                    self.format_args(&param_types)
                ));
                method.push_str(&self.generate_original_callWithReturn(
                    &entry.target_method,
                    &param_types,
                    &return_type,
                    "result",
                ));
                method.push_str(&format!(
                    "        HookBridge.callHandler(MODULE_ID, {}, new Object[]{{ \"after\", result }});\n",
                    hook_id
                ));
                method.push_str("        return result;\n");
            }
        }

        method.push_str("    }\n");
        method
    }

    /// 解析 JVM 方法签名
    ///
    /// 例如：(Ljava/lang/String;I)V → (["Ljava/lang/String;", "I"], "V")
    fn parse_signature(&self, sig: &str) -> (Vec<String>, String) {
        if !sig.starts_with('(') {
            return (Vec::new(), "V".to_string());
        }
        let close = match sig.find(')') {
            Some(p) => p,
            None => return (Vec::new(), "V".to_string()),
        };
        let params_str = &sig[1..close];
        let return_type = &sig[close + 1..];

        let mut params = Vec::new();
        let mut chars = params_str.chars().peekable();
        while let Some(&c) = chars.peek() {
            match c {
                'L' => {
                    // 对象类型 Lpackage/Class;
                    let mut p = String::from("L");
                    chars.next();
                    while let Some(&ch) = chars.peek() {
                        p.push(ch);
                        chars.next();
                        if ch == ';' {
                            break;
                        }
                    }
                    params.push(p);
                }
                '[' => {
                    // 数组类型
                    let mut p = String::from("[");
                    chars.next();
                    if let Some(&next) = chars.peek() {
                        if next == 'L' {
                            p.push('L');
                            chars.next();
                            while let Some(&ch) = chars.peek() {
                                p.push(ch);
                                chars.next();
                                if ch == ';' {
                                    break;
                                }
                            }
                        } else {
                            p.push(next);
                            chars.next();
                        }
                    }
                    params.push(p);
                }
                _ => {
                    // 基本类型
                    params.push(c.to_string());
                    chars.next();
                }
            }
        }

        (params, return_type.to_string())
    }

    /// 把 JVM 类型签名转为 Java 类型名
    fn jvm_type_to_java(&self, jvm_type: &str) -> String {
        if jvm_type.starts_with('L') && jvm_type.ends_with(';') {
            // Lpackage/Class; → package.Class
            jvm_type[1..jvm_type.len() - 1].replace('/', ".")
        } else if jvm_type.starts_with('[') {
            // 数组
            format!("{}[]", self.jvm_type_to_java(&jvm_type[1..]))
        } else {
            match jvm_type {
                "V" => "void",
                "Z" => "boolean",
                "B" => "byte",
                "C" => "char",
                "S" => "short",
                "I" => "int",
                "J" => "long",
                "F" => "float",
                "D" => "double",
                _ => "Object",
            }
            .to_string()
        }
    }

    /// 格式化方法参数
    fn format_params(&self, param_types: &[String]) -> String {
        param_types
            .iter()
            .enumerate()
            .map(|(i, t)| format!("{} arg{}", self.jvm_type_to_java(t), i))
            .collect::<Vec<_>>()
            .join(", ")
    }

    /// 格式化参数引用
    fn format_args(&self, param_types: &[String]) -> String {
        (0..param_types.len())
            .map(|i| format!("arg{}", i))
            .collect::<Vec<_>>()
            .join(", ")
    }

    /// 生成原方法调用（无返回值）
    fn generate_original_call(&self, method: &str, params: &[String], return_type: &str) -> String {
        let args = (0..params.len())
            .map(|i| format!("arg{}", i))
            .collect::<Vec<_>>()
            .join(", ");
        if return_type == "V" {
            format!("        original.{}({});\n", method, args)
        } else {
            format!("        return original.{}({});\n", method, args)
        }
    }

    /// 生成原方法调用（带返回值赋给变量）
    fn generate_original_callWithReturn(
        &self,
        method: &str,
        params: &[String],
        return_type: &str,
        var_name: &str,
    ) -> String {
        let args = (0..params.len())
            .map(|i| format!("arg{}", i))
            .collect::<Vec<_>>()
            .join(", ");
        let java_type = self.jvm_type_to_java(return_type);
        format!(
            "        {} {} = original.{}({});\n",
            java_type, var_name, method, args
        )
    }

    /// 从 Object 生成 return 语句
    fn generate_return_from_object(&self, return_type: &str, var_name: &str) -> String {
        match return_type {
            "V" => "        return;\n".to_string(),
            "Z" => format!("        return (Boolean) {};\n", var_name),
            "B" => format!("        return (Byte) {};\n", var_name),
            "C" => format!("        return (Character) {};\n", var_name),
            "S" => format!("        return (Short) {};\n", var_name),
            "I" => format!("        return (Integer) {};\n", var_name),
            "J" => format!("        return (Long) {};\n", var_name),
            "F" => format!("        return (Float) {};\n", var_name),
            "D" => format!("        return (Double) {};\n", var_name),
            _ => format!(
                "        return ({}) {};\n",
                self.jvm_type_to_java(return_type),
                var_name
            ),
        }
    }
}

impl Default for ArtHookGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_signature_void_no_params() {
        let gen = ArtHookGenerator::new();
        let (params, ret) = gen.parse_signature("()V");
        assert!(params.is_empty());
        assert_eq!(ret, "V");
    }

    #[test]
    fn test_parse_signature_string_return_int() {
        let gen = ArtHookGenerator::new();
        let (params, ret) = gen.parse_signature("(Ljava/lang/String;)I");
        assert_eq!(params, vec!["Ljava/lang/String;".to_string()]);
        assert_eq!(ret, "I");
    }

    #[test]
    fn test_parse_signature_multiple_params() {
        let gen = ArtHookGenerator::new();
        let (params, ret) = gen.parse_signature("(Ljava/lang/String;IZ)V");
        assert_eq!(params.len(), 3);
        assert_eq!(params[0], "Ljava/lang/String;");
        assert_eq!(params[1], "I");
        assert_eq!(params[2], "Z");
        assert_eq!(ret, "V");
    }

    #[test]
    fn test_parse_signature_array_param() {
        let gen = ArtHookGenerator::new();
        let (params, _) = gen.parse_signature("([Ljava/lang/String;)V");
        assert_eq!(params, vec!["[Ljava/lang/String;".to_string()]);
    }

    #[test]
    fn test_jvm_type_to_java() {
        let gen = ArtHookGenerator::new();
        assert_eq!(gen.jvm_type_to_java("V"), "void");
        assert_eq!(gen.jvm_type_to_java("Z"), "boolean");
        assert_eq!(gen.jvm_type_to_java("I"), "int");
        assert_eq!(gen.jvm_type_to_java("J"), "long");
        assert_eq!(
            gen.jvm_type_to_java("Ljava/lang/String;"),
            "java.lang.String"
        );
        assert_eq!(gen.jvm_type_to_java("[I"), "int[]");
        assert_eq!(
            gen.jvm_type_to_java("[Ljava/lang/String;"),
            "java.lang.String[]"
        );
    }

    #[test]
    fn test_generate_proxy_class_name() {
        let gen = ArtHookGenerator::new();
        let name = gen.make_proxy_class_name("test_mod", "android.app.ActivityManager");
        assert!(name.starts_with("NexusHook_test_mod_"));
        assert_eq!(name.len(), "NexusHook_test_mod_".len() + 8);
    }

    #[test]
    fn test_generate_creates_classes() {
        let mut gen = ArtHookGenerator::new();
        let mut table = HookTable::default();
        table.entries.push(HookEntry {
            target_class: "android.app.Activity".to_string(),
            target_method: "onCreate".to_string(),
            signature: "(Landroid/os/Bundle;)V".to_string(),
            hook_type: HookType::After,
            handler: "log_activity".to_string(),
            params: HashMap::new(),
        });
        let result = gen.generate(&table, "test_mod");
        assert_eq!(result.len(), 1);
        assert!(result[0].0.starts_with("NexusHook_test_mod_"));
        // 验证生成的 Java 源码包含关键元素
        let java = &result[0].1;
        assert!(java.contains("package com.nexus.hook.generated"));
        assert!(java.contains("import com.nexus.hook.runtime.HookBridge"));
        assert!(java.contains("MODULE_ID"));
        assert!(java.contains("registerHook"));
    }

    #[test]
    fn test_generate_replace_hook() {
        let mut gen = ArtHookGenerator::new();
        let mut table = HookTable::default();
        table.entries.push(HookEntry {
            target_class: "android.location.Location".to_string(),
            target_method: "getLatitude".to_string(),
            signature: "()D".to_string(),
            hook_type: HookType::Replace,
            handler: "fake_location".to_string(),
            params: HashMap::new(),
        });
        let result = gen.generate(&table, "loc_mod");
        assert_eq!(result.len(), 1);
        let java = &result[0].1;
        // Replace 类型应包含 callHandler
        assert!(java.contains("callHandler"));
    }

    #[test]
    fn test_generate_multiple_hooks_same_class() {
        let mut gen = ArtHookGenerator::new();
        let mut table = HookTable::default();
        table.entries.push(HookEntry {
            target_class: "android.location.Location".to_string(),
            target_method: "getLatitude".to_string(),
            signature: "()D".to_string(),
            hook_type: HookType::Replace,
            handler: "fake_lat".to_string(),
            params: HashMap::new(),
        });
        table.entries.push(HookEntry {
            target_class: "android.location.Location".to_string(),
            target_method: "getLongitude".to_string(),
            signature: "()D".to_string(),
            hook_type: HookType::Replace,
            handler: "fake_lng".to_string(),
            params: HashMap::new(),
        });
        let result = gen.generate(&table, "loc_mod");
        // 两个 hook 同一 class 应生成一个代理类
        assert_eq!(result.len(), 1);
        let java = &result[0].1;
        // 应包含两个 registerHook 方法
        assert!(java.contains("registerHook_0"));
        assert!(java.contains("registerHook_1"));
    }

    #[test]
    fn test_generate_different_classes() {
        let mut gen = ArtHookGenerator::new();
        let mut table = HookTable::default();
        table.entries.push(HookEntry {
            target_class: "android.app.Activity".to_string(),
            target_method: "onCreate".to_string(),
            signature: "(Landroid/os/Bundle;)V".to_string(),
            hook_type: HookType::After,
            handler: "log1".to_string(),
            params: HashMap::new(),
        });
        table.entries.push(HookEntry {
            target_class: "java.lang.Runtime".to_string(),
            target_method: "exec".to_string(),
            signature: "(Ljava/lang/String;)Ljava/lang/Process;".to_string(),
            hook_type: HookType::Before,
            handler: "log2".to_string(),
            params: HashMap::new(),
        });
        let result = gen.generate(&table, "multi_mod");
        // 两个不同 class 应生成两个代理类
        assert_eq!(result.len(), 2);
    }
}
